@startuml ユースケース図
left to right direction
'次の文章の条件を満たすオブジェクト図を完成させなさい。なお、属性に具体的な値があるクラスは属性値を表記し、ないクラスは省略形で表記しなさい。
'AさんとBさんがホテルUMLに宿泊をしました。客室のタイプはシングル、宿泊費は一泊11,000円、キャンペーン価格9,000円の部屋です。チャックイン日は、5月3日で2泊の予定です。4月29日から5月6日まではキャンペーン期間です。システムはAさんの宿泊予定の客室を301号室、Bさんの宿泊予定の客室を304号室としました。
'1.予約のオブジェクトは、省略する
'2.へやのオブジェクト名は、301号室、302号室とする

object "<u>客1:顧客</u>" as A {
名前=Aさん
住所
電話番号
}
object "<u>客2:顧客</u>" as B {
名前=Bさん
住所
電話番号
}

object "<u>301号:ルーム</u>" as 301 {
    タイプ=シングル
    価格=11,000
    キャンペーン価格=9,000円
}

object "<u>302号:ルーム</u>" as 302 {
    タイプ=シングル
    価格=11,000
    キャンペーン価格=9,000円
}

object "<u>303号:ルーム</u>" as 303 {
    タイプ=シングル
    価格=11,000
    キャンペーン価格=9,000円
}

object "<u>ホテル:ホテル</u>" as h {
部屋
}
h -- 301
h -- 302
h -- 303
A -- 301
B -- 303
@enduml