@startuml プリント
[*] -> メニュー :接続
メニュー --> 予約と確認 :予約と確認を選択する
予約と確認 -> メニュー :取り消しボタンを押す
予約と確認 -right-> 貴方の順番 :登録ボタンを押す
予約と確認 -right-> 貴方の順番 :確認ボタンを押す
貴方の順番 -up-> メニュー :メニューボタンを押す
メニュー -> 今の順番 :今の順番ボタンを押す
今の順番 --> メニュー :メニューボタンを押す
メニュー-> [*] :切断
@enduml