@startuml
hide footbox
participant ":利用者：user" as user
participant ":ログイン" as login

mainframe sd ログイン
activate user
activate login

user ->> login : ログインメッセージを送る()
login -> login : 確認操作()
activate login
deactivate login
@enduml