@startuml 予約
hide footbox
participant ":データ更新コントローラ" as control
participant ":ホテル" as hotel
participant ":予約" as Y 
' 厳密なUMLに準拠する
skinparam style strictuml

activate control
activate hotel

control -> hotel : 予約する()
create Y
hotel -> Y : <<create>>

hotel -> hotel: 予約登録()
activate hotel
deactivate hotel

@enduml