@startuml
hide footbox
Actor 客 as customer
participant ":フロア店員" as salesperson
participant ":料理人" as cook
mainframe sd ラーメン屋さん

activate customer
customer -> salesperson : ラーメンを注文

activate salesperson
salesperson -> cook : 調理を指示する

activate cook
cook -> cook :調理をする
salesperson <<-- cook : ラーメン
deactivate cook
customer <<-- salesperson : ラーメン
deactivate salesperson
@enduml