' 次のシーケンスを満たすように、シーケンス図を作成しなさい。同期メッセージに関してはリターンも表記すること。
' １.利用者クラスのオブジェクトuserは、ログインを行う（予約画面にログインメッセージを送る）
' また、ログインメッセージは非同期とする
' ２．次に予約画面クラスのオブジェクトは、自分自身の確認操作(認証）を呼び出す（同期）
@startuml 
hide footbox
participant ":利用者：user" as user
participant ":ログイン" as login
activate user

activate login
user ->> login : ログインメッセージを送る()
login -> login : 確認操作()
activate login
deactivate login
deactivate user
@enduml