@startuml ユースケース図
'ホテルには部屋が複数個（いくつかは不明）あります。
'ホテルには利用者が会員として登録されています。
'利用者は部屋を予約します。
class 利用者 {
-名前
-住所
-電話番号
}

class ホテル {
-部屋
}

class 部屋 {
-タイプ
-価格
-キャンペーン価格
}

class 予約 {
-チェックイン日
-滞在期間
-値段
}

ホテル "1"*--"*" 部屋
ホテル "1"--"*" 利用者 :会員
予約 "1"--"1" 利用者
