@startuml ユースケース図
left to right direction
'医師は患者を診察します。医師は診察のつどに、患者の診察記録を作成します。
'患者には担当医が1人決まっていて、担当医以外が診察することはありません。
'医師は１つの医局（外科、内科、小児科など）に所属しています。
'※多重度、関連名、関連端名なども反映してください。
class 医師 {
-名前:String
}

class 患者 {
-名前:String
-担当医:String
}

class 医局 {
    
}

class 診察記録 {
-日付:Date
-審査結果:String
-担当医:String
}


医師 "1"-->"*" 患者 :担当する
医局 <-- 医師 :所属する
診察記録 "*"--"1" 患者
診察記録 <-- 医師 :作る